development:
  adapter: postgresql
  encoding: utf8
  database: tcgl_server_desenvolvimento
  username: postgres
  password: appoloex
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: tcgl_server_teste
  username: postgres
  password: appoloex
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: tcgl_server_producao
  username: postgres
  password: appoloex
  host: localhost
